services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8003:8003"
      - "8004:8004"
    environment:
      - AC_SECRET=your_jwt_secret
      - RF_SECRET=your_refresh_secret
      - DB_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - MONGO_URL=mongodb://mongo:27017

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6.0-jammy
    volumes:
      - mongodb_data:/data/db

volumes:
  postgres_data:
  mongodb_data: