apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-postgres
  template:
    metadata:
      labels:
        app: chat-postgres
    spec:
      containers:
        - name: chat-postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "abdullah"
            - name: POSTGRES_DB
              value: "my_db"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}